### ISSUE TITLE
[BUG] Docker: Unable to configure database properties using: CLI arguments, env variables and spring profiles

### ISSUE THREAD

**Issue by aringeri** [cBioPortal/cbioportal#11553]
**Describe the bug**

When running with the docker image: cbioportal/cbioportal:6.0.24

I am unable to set the mysql database properties using command line argument without also having them in the application properties.

```bash
java -Xms2g -Xmx4g -cp '/cbioportal-webapp:/cbioportal-webapp/lib/*' org.cbioportal.PortalApplication \
    --spring.config.location=cbioportal-webapp/application.properties \
    --spring.datasource.username=${DATASOURCE_USERNAME}
    --spring.datasource.password=${DATASOURCE_PASSWORD}
```

The entrypoint (`docker-entrypoint.sh`) for the docker image expects everything to be set in the application.properties file and gives:
```
Missing required properties : (spring.datasource.username, spring.datasource.password)
failure reading properties file (/cbioportal-webapp/application.properties)
```

**To Reproduce**
- clone https://github.com/cBioPortal/cbioportal-docker-compose
- modify the docker-compose.yml command to look something like

```yaml
...
 cbioportal:
    restart: unless-stopped
    image: ${DOCKER_IMAGE_CBIOPORTAL}
    container_name: cbioportal-container
    environment:
      SHOW_DEBUG_INFO: "true"
      PORTAL_HOME: "/cbioportal-webapp"
    ports:
      - "8080:8080"
    volumes:
     - ./study:/study/
     - ${APPLICATION_PROPERTIES_PATH:-./config/application.properties}:/cbioportal-webapp/application.properties:ro
    depends_on:
     - cbioportal-database
     - cbioportal-session
    networks:
     - cbio-net
    command: /bin/sh -c "
        java -Xms2g -Xmx4g -cp '/cbioportal-webapp:/cbioportal-webapp/lib/*' org.cbioportal.PortalApplication 
          --spring.config.location=cbioportal-webapp/application.properties 
          --authenticate=false 
          --session.service.url=http://cbioportal-session:5001/api/sessions/my_portal/ 
          --clickhouse_mode=$${APP_CLICKHOUSE_MODE:-false} 
          --spring.profiles.active=$${APP_SPRING_PROFILE:-default}
          --spring.datasource.username=${DATASOURCE_USERNAME}
          --spring.datasource.password=${DATASOURCE_PASSWORD}
       "
 ...
```

Even using `-Dspring.datasource.username=...` is not working.

**Expected behavior**
I would expect that the docker version of cbioportal to support the 'spring' way of handling configuration.
We should be able to set properties using any of the following:
- CLI `--spring.datasource.username=X`
- CLI `-Dspring.datasource.username=X`
- environment `SPRING_DATASOURCE_USERNAME=X' see ([binding from environment variables](https://docs.spring.io/spring-boot/docs/2.1.x/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding-from-environment-variables))
- spring profiles: there could be the option of additional `application-{profile}.properties` files that hold db config.

**Additional context**
Using an entrypoint script to migrate the db on start can be quite limiting especially if it runs in a bash script and cannot load the full spring context.
I think by at least having an option to set the db params through the CLI or environment variable would be ideal. It means we can share configuration between the database container and cbioportal container.

Happy to hear your thoughts.
