### ISSUE TITLE
docker compose breaks on macbook m1

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9829]
Getting some osx thread issues and platform not supported on latest macbook m1. Had to create a `docker-compose.override.yml` like this:

```
version: '3'

services:
  cbioportal:
    image: cbioportal/cbioportal:5.2.4
  cbioportal-database:
    image: biarms/mysql:5.7
  cbioportal-session:
    image: cbioportal/session-service:0.6.0
  cbioportal-session-database:
    image: mongo:4.2
```

EDIT: Updated the above with pre-released versions of cbioportal and session service

**Comment by ndfriedman** [comment]
@inodb how should I add these changes?  Replace the original "docker-compose.yml" with this file?  Or add this file to the docker-compose file and point to it?  Or replace the specific lines above inside the original "docker-compose.yml"?

**Comment by inodb** [comment]
@ndfriedman you add a file in the same folder called `docker-compose.override.yml`. This currently seems to work:

```
version: '3'

services:
  cbioportal:
    image: cbioportal/cbioportal:demo-support-multi-platform-images
  cbioportal-database:
    image: biarms/mysql:5.7
  cbioportal-session:
    image: cbioportal/session-service:test-arm64
  cbioportal-session-database:
    image: mongo:4.2
```
