### ISSUE TITLE
Expression profiles in Plots tab show wrong labels and should not be compared

### ISSUE THREAD

**Issue by SRodenburg** [cBioPortal/cbioportal#9865]
I found something strange in Plots tab for expression profiles - not sure if it's by design.

It is currently not possible to compare expression (or anything other than clinical/mutations/CNA) in Group Comparison if you selected multiple studies. I think this was disabled because the studies might have used different expression units, pipelines, etc etc. In other words, cBioPortal has no way of knowing what the values actually mean and whether they are comparable between studies.

In the Plots tab, however, comparison of expression values between studies is possible. The expression profiles that are available for plotting are determined by the `stable_id` field of the expression file. Only a handful of different stable ID values are allowed ([see docs](https://docs.cbioportal.org/file-formats/#supported-stable_id-values-for-mrna_expression)). 

The problem is that these stable IDs do not enforce that the actual data that is shown, is actually representing the same thing, think of expression units: TPM/FPKM/Counts nor the pipeline that is used. The Plots tab does however, and this is clearly wrong, collapse the available  mRNA profiles  under a single label, and ignores the others. This can lead to misleading/wrong information in the UI on the plotting axes. See the toy example below.

Two copies of `study_es_0`, both expression files have different values for `profile_name` and `profile_description`, and illustrate a scenario where these would represent different units.

**study_es_0**:
```yaml
cancer_study_identifier: study_es_0
genetic_alteration_type: MRNA_EXPRESSION
datatype: CONTINUOUS
stable_id: mrna
profile_description: THESE ARE FPKM VALUES
show_profile_in_analysis_tab: false
profile_name: FPKM!!!!
data_filename: data_expression_median.txt
```

**study_es_0-1**
```yaml
cancer_study_identifier: study_es_0-1
genetic_alteration_type: MRNA_EXPRESSION
datatype: CONTINUOUS
stable_id: mrna
profile_description: THIS IS TPM VALUES
show_profile_in_analysis_tab: false
profile_name: TPM VALUES!!!!!
data_filename: data_expression_median.txt
```

Now in the Plots tab, you are able to plot these onto the same axis - even indicating units - even though they represent different things:
![image](https://user-images.githubusercontent.com/23449704/198038197-adccba96-e419-4f37-bce1-1e5500f5e3c9.png)

In my opinion, we should either:
- not collapse on `stable_id`
- allow __any__ stable ID so we can at least use stable IDs such as `mrna_fpkm`, in that sense a collapse under the same label is less of an issue
- not allow cross-comparison of RNA-Seq at all
